regular:
  - angle-left
  - angle-right
  - bag-shopping
  - bars
  - building
  - chair
  - check
  - chevron-right
  - circle-info
  - clone
  - copyright
  - cubes
  - eye
  - folder-tree
  - gears
  - hammer
  - lightbulb
  - list
  - location-dot
  - pencil
  - shop
  - store
  - right-left
  - right-to-bracket
  - tree
  - up-right-and-down-left-from-center
  - xmark