light:
  - angle-left
  - angle-right
  - arrow-down
  - arrow-up
  - bag-shopping
  - bars
  - building
  - cart-shopping
  - chair
  - check
  - chevron-right
  - circle-info
  - clock
  - clock-rotate-left
  - clone
  - copyright
  - cubes
  - ellipsis-vertical
  - eye
  - folder-tree
  - gear
  - gears
  - gift-card
  - hammer
  - laptop
  - lightbulb
  - list
  - list-tree
  - location-dot
  - magnifying-glass
  - minus
  - pencil
  - plus
  - shop
  - store
  - right-left
  - right-to-bracket
  - trash
  - tree
  - up-right-and-down-left-from-center
  - xmark
regular:
  - angle-left